"""Central runtime defaults."""

DEFAULT_SOURCE_LANGUAGE = "auto"
DEFAULT_TARGET_LANGUAGE = "es"
DEFAULT_SAMPLE_RATE = 16000
DEFAULT_CHANNELS = 2
DEFAULT_AUDIO_BLOCK_FRAMES = 2048
DEFAULT_ASR_MODEL = "small"
DEFAULT_ASR_DEVICE = "cpu"
DEFAULT_ASR_COMPUTE_TYPE = "int8"
DEFAULT_MAX_UTTERANCE_SECONDS = 18.0
DEFAULT_SILENCE_CHUNKS = 8
DEFAULT_MAX_BUFFER_CHUNKS = 160
